### ISSUE TITLE
[FEATURE] implement a versioning and changelog system

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#75]
you can just explain the process, based on your experience with other projects.

for things only admins can do on this repo, just tag me @FrancescoXX

**Comment by Pradumnasaraf** [comment]
Hey, @FrancescoXX  it will be really simple to implement.

### Steps:

- Create a file called `releases.yml` (Of course, you can name it anything, but this is more understandable) inside the `workflows` folder, which is inside your `.github` folder located in the root. So, the path will look like this: `.github/workflows/releases.yml`

- Copy the below configuration. The workflow needs write permission to create tags and releases, so we need to give write permission.

```yaml
name: Releases and Changelog
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './package.json,./package-lock.json'

      - name: Create Release
        if: steps.changelog.outputs.skipped == 'false'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```

Let me know if you need any help :)

Also, change the https://github.com/FrancescoXX/rustcrab/labels/documentation issue label to something to CI/automation or something different.
